### PR TITLE
Extend initialization equations

### LINKED ISSUE #2845: extend() does not pass on initialization equations
This does not work:
```julia
using Test
using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D

@variables x(t) y(t)
@named sysx = ODESystem([D(x) ~ 0], t; initialization_eqs = [x ~ 1])
@named sysy = ODESystem([D(y) ~ 0], t; initialization_eqs = [y ~ 2])
sys = extend(sysx, sysy)
@test length(equations(generate_initializesystem(sys))) == 2
```

### PR DESCRIPTION
**Pull request by hersle**
Fixes #2845

## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

File: src/systems/abstractsystem.jl [hunk 1]
```diff
@@ -2528,16 +2528,19 @@ function extend(sys::AbstractSystem, basesys::AbstractSystem; name::Symbol = nam
     cevs = union(get_continuous_events(basesys), get_continuous_events(sys))
     devs = union(get_discrete_events(basesys), get_discrete_events(sys))
     defs = merge(get_defaults(basesys), get_defaults(sys)) # prefer `sys`
+    guesses = merge(get_guesses(basesys), get_guesses(sys)) # prefer `sys`
```
Comment (ChrisRackauckas) [inline src/systems/abstractsystem.jl:2531]: This needs to check if the system has guesses and initialization. It would be fine to just check if odesystem.

Comment (hersle) [reply src/systems/abstractsystem.jl]: I see, thanks. I added a test like that now.
