### PR TITLE
fix: Add metadata getters

### LINKED ISSUE #2643: Missing metadata getters
It seems that getters for these metadata are missing: `misc`, `input`. Possibly this holds for a few others.

### PR DESCRIPTION
**Pull request by vyudu**
Fixes #2643. Adds getters for `connect, unit, misc`

### CODE REVIEW

**Comment by vyudu** [comment]
@AayushSabharwal Haven't change `vartype` to `variable_source` in this PR but let me know if I should add it.

**Comment by AayushSabharwal** [comment]
Yeah go for it

**Comment by ChrisRackauckas** [comment]
add to the docs section on metadata?

**Comment by vyudu** [comment]
This one should be ready

File: src/variables.jl [hunk 1]
```diff
@@ -57,16 +55,16 @@ function dump_variable_metadata(var)
     disturbance = isdisturbance(uvar) || nothing
     tunable = istunable(uvar, isparameter(uvar))
     dist = getdist(uvar)
-    type = symtype(uvar)
+    variable_type = getvariabletype(uvar)
 
     meta = (
         var = var,
-        vartype,
+        variable_source,
```
Comment (AayushSabharwal) [inline src/variables.jl:62]: Changing this key is breaking

File: docs/src/basics/Variable_metadata.md [hunk 2]
```diff
@@ -177,8 +181,44 @@ A variable can be marked `irreducible` to prevent it from being moved to an
...
+When a model is structurally simplified, the algorithm will try to ensure that the variables with higher state priority become states of the system. A variable's state priority is a number set using the `state_priority` metadata.
+
+```@example metadata
+@variable important_dof [state_priority = 10] unimportant_dof [state_priority = 2]
+state_priority(important_dof)
+```
+
+## Units
+
+Units for variables can be designated using symbolic metadata. For more information, please see the [model validation and units](@ref units) section of the docs. Note that `getunit` is equivalent to `get_unit`.
```
Comment (AayushSabharwal) [inline docs/src/basics/Variable_metadata.md:200]: `getunit` and `get_unit` aren't equivalent

**Review by AayushSabharwal — CHANGES_REQUESTED** [review]

File: docs/src/basics/Variable_metadata.md (hunk 2 above)
Comment (AayushSabharwal) [reply docs/src/basics/Variable_metadata.md:200]: Ah never mind, I read the code wrong

File: src/variables.jl (hunk 1 above)
Comment (ChrisRackauckas) [reply src/variables.jl:62]: what will it break?

Comment (AayushSabharwal) [reply src/variables.jl:62]: `dump_unknowns` and `dump_parameters` are public API, and they return an array of these `NamedTuple`s. If a user is relying on the `vartype` key, changing it breaks their code.

Comment (ChrisRackauckas) [reply src/variables.jl:62]: I wouldn't say that's breaking. We don't guarantee what metadata is returned and we have changed that before.

Comment (ChrisRackauckas) [reply src/variables.jl:62]: But I guess the real question is, do we need to do the break? What's the motivation for the name change?

Comment (AayushSabharwal) [reply src/variables.jl:62]: > We don't guarantee what metadata is returned

If that's the case, sure. 

> we have changed that before.

We've only every added entries, which isn't breaking

> do we need to do the break? What's the motivation for the name change?

@vyudu brought up that it is inconsistently named and more importantly, doesn't accurately reflect the type of the variable. The `VariableSource` metadata tells which macro this variable came from, but whether it's a parameter/unknown actually depends on the `MTKVariableTypeCtx` metadata.

**Comment by vyudu** [comment]
Sorry @AayushSabharwal I just realized that my replies were Pending and never got submitted. I thought we wanted vartype to be renamed in this PR? https://github.com/SciML/ModelingToolkit.jl/pull/3334#issuecomment-2596780414 If not I can revert

File: src/variables.jl (hunk 1 above)
Comment (ChrisRackauckas) [reply src/variables.jl:62]: Alright, this is better and I don't think it's breaking.

**Comment by vyudu** [comment]
@ChrisRackauckas this one is ready

File: docs/src/basics/Variable_metadata.md [hunk 3]
```diff
@@ -177,8 +181,44 @@ A variable can be marked `irreducible` to prevent it from being moved to an
...
 @variable important_value [irreducible = true]
+isirreducible(important_value)
+```
+
+## State Priority
+
+When a model is structurally simplified, the algorithm will try to ensure that the variables with higher state priority become states of the system. A variable's state priority is a number set using the `state_priority` metadata.
+
+```@example metadata
+@variable important_dof [state_priority = 10] unimportant_dof [state_priority = 2]
```
Comment (ChrisRackauckas) [inline docs/src/basics/Variable_metadata.md:194]:
```suggestion
@variable important_dof [state_priority = 10] unimportant_dof [state_priority = -2]
```

**Review by ChrisRackauckas — APPROVED** [review]
