### PR TITLE
fix: fix values being promoted to `Float64` in problem construction

### LINKED ISSUE #3553: `Float32` types are automatically converted to `Float64`
```julia
using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D
using OrdinaryDiffEq
@parameters p d
@variables X(t)
eqs = [D(X) ~ p - d*X]
@mtkbuild osys = ODESystem(eqs, t)
u0 = [X => 1.0f0]
ps = [p => 1.0f0, d => 2.0f0]
oprob = ODEProblem(osys, u0, 1.0, ps)
sol = solve(oprob)

typeof(oprob[X]) # Float64
eltype(sol[X]) # Float64
```
This one popped out in the Catalyst tests with the latest MTK release. Among other things it should be a major problem for GPU parallelisation.

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Close #3553

### CODE REVIEW

File: src/systems/abstractsystem.jl [hunk 1]
```diff
@@ -733,11 +733,11 @@ function add_initialization_parameters(sys::AbstractSystem)
     defs = copy(get_defaults(sys))
     for ivar in initials
         if symbolic_type(ivar) == ScalarSymbolic()
-            defs[ivar] = zero_var(ivar)
+            defs[ivar] = zero(Float16)
         else
             defs[ivar] = collect(ivar)
             for scal_ivar in defs[ivar]
-                defs[scal_ivar] = zero_var(scal_ivar)
+                defs[scal_ivar] = zero(Float16)
```
Comment (ChrisRackauckas) [inline src/systems/abstractsystem.jl:740]:
```suggestion
                defs[scal_ivar] = false
```

File: src/systems/nonlinear/initializesystem.jl [hunk 2]
```diff
@@ -8,7 +8,7 @@ function generate_initializesystem(sys::AbstractTimeDependentSystem;
         pmap = Dict(),
         initialization_eqs = [],
         guesses = Dict(),
-        default_dd_guess = 0.0,
+        default_dd_guess = Bool(0),
```
Comment (ChrisRackauckas) [inline src/systems/nonlinear/initializesystem.jl:11]: Just false?

Comment (AayushSabharwal) [reply src/systems/nonlinear/initializesystem.jl:11]: `false` makes the kwarg seem like a flag, when it is actually a value. So I opted for `Bool(0)` just to make it clearer.

**Comment by AayushSabharwal** [comment]
_Finally_
