### PR TITLE
fix: copy initials to `u0` if `u0` not provided to `remake`

### LINKED ISSUE #3570: setting `Initial`s is ignorred when using `BrownFullBasicInit`
**Describe the bug 🐞**

Changing `Initial`s with `setsym_oop` does not work when using `initializealg = BrownFullBasicInit()` when we have initial overrides.

**Expected behavior**

I would have expected this to work

**Minimal Reproducible Example 👇**

Without MRE, we would only be able to help you to a limited extent, and attention to the issue would be limited. to know more about MRE refer to [wikipedia](https://en.wikipedia.org/wiki/Minimal_reproducible_example) and [stackoverflow](https://stackoverflow.com/help/minimal-reproducible-example).

```julia
using ModelingToolkit, OrdinaryDiffEqDefault, OrdinaryDiffEqNonlinearSolve
using ModelingToolkit: t_nounits as t, D_nounits as D
using SymbolicIndexingInterface

@parameters g
@variables x(t) [state_priority = 10] y(t) λ(t)
eqs = [D(D(x)) ~ λ * x
       D(D(y)) ~ λ * y - g
       x^2 + y^2 ~ 1]
@mtkbuild pend = ODESystem(eqs, t)

prob = ODEProblem(pend, [x => (√2/2)], (0.0, 1.5), [g => 1], guesses = [λ => 1, y=>√2/2])
sol = solve(prob)

setter = setsym_oop(prob, [Initial(x)]);
(u0, p) = setter(prob, [0.8])

new_prob = remake(prob; u0, p, initializealg = BrownFullBasicInit())
new_sol = solve(new_prob)
new_sol[[x], 1] # √2/2 instead of 0.8
```

If I remove `initializealg` from the above `remake` call, then I get the expected answer of 0.8.

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `/tmp/jl_fOiWV1/Project.toml`
  [961ee093] ModelingToolkit v9.72.0
  [50262376] OrdinaryDiffEqDefault v1.3.0
  [127b3ac7] OrdinaryDiffEqNonlinearSolve v1.6.0
  [2efcf032] SymbolicIndexingInterface v0.3.39
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
Status `/tmp/jl_fOiWV1/Manifest.toml`
  [47edcb42] ADTypes v1.14.0
  [1520ce14] AbstractTrees v0.4.5
  [7d9f7c33] Accessors v0.1.42
  [79e6a3ab] Adapt v4.3.0
  [66dad0bd] AliasTables v1.1.3
  [ec485272] ArnoldiMethod v0.4.0
  [4fba245c] ArrayInterface v7.18.0
  [4c555306] ArrayLayouts v1.11.1
  [e2ed5e7c] Bijections v0.1.9
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [8e7c35d0] BlockArrays v1.6.1
  [70df07ce] BracketingNonlinearSolve v1.1.3
  [2a0fbf3d] CPUSummary v0.2.6
  [00ebfdb7] CSTParser v3.4.3
  [d360d2e6] ChainRulesCore v1.25.1
  [fb6a15b2] CloseOpenIntervals v0.1.13
  [861a8166] Combinatorics v1.0.2
⌅ [a80b9123] CommonMark v0.8.16
  [38540f10] CommonSolve v0.2.4
  [bbf7d656] CommonSubexpressions v0.3.1
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.16.0
  [b152e2b5] CompositeTypes v0.1.4
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.5.8
  [adafc99b] CpuId v0.3.1
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [864edb3b] DataStructures v0.18.22
  [e2d170a0] DataValueInterfaces v1.0.0
  [2b5f629d] DiffEqBase v6.167.2
  [459566f4] DiffEqCallbacks v4.4.0
  [77a26b50] DiffEqNoiseProcess v5.24.1
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.6.52
  [8d63f2c5] DispatchDoctor v0.4.19
  [31c24e10] Distributions v0.25.119
  [ffbed154] DocStringExtensions v0.9.4
  [5b8099bc] DomainSets v0.7.15
  [7c1d4256] DynamicPolynomials v0.6.1
  [06fc5a27] DynamicQuantities v1.8.0
  [4e289a0a] EnumX v1.0.5
  [f151be2c] EnzymeCore v0.8.8
  [e2ba6199] ExprTools v0.1.10
  [55351af7] ExproniconLite v0.10.14
  [7034ab61] FastBroadcast v0.3.5
  [9aa1b823] FastClosures v0.3.2
  [a4df4552] FastPower v1.1.2
  [1a297f60] FillArrays v1.13.0
  [64ca27bc] FindFirstFunctions v1.4.1
  [6a86dc24] FiniteDiff v2.27.0
  [1fa38f19] Format v1.3.7
⌅ [f6369f11] ForwardDiff v0.10.38
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [d9f16b24] Functors v0.5.2
  [46192b85] GPUArraysCore v0.2.0
  [c27321d9] Glob v1.3.1
  [86223c79] Graphs v1.12.1
  [34004b35] HypergeometricFunctions v0.3.28
  [615f187c] IfElse v0.1.1
  [d25df0c9] Inflate v0.1.5
  [18e54dd8] IntegerMathUtils v0.1.2
  [8197267c] IntervalSets v0.7.10
  [3587e190] InverseFunctions v0.1.17
  [92d709cd] IrrationalConstants v0.2.4
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.7.0
  [ae98c720] Jieko v0.2.1
⌅ [98e50ef6] JuliaFormatter v1.0.62
  [ccbc3e58] JumpProcesses v9.14.3
  [ba0b0d4f] Krylov v0.9.10
  [b964fa9f] LaTeXStrings v1.4.0
  [23fbe1c1] Latexify v0.16.7
  [10f19ff3] LayoutPointers v0.1.17
  [5078a376] LazyArrays v2.6.1
  [87fe0de2] LineSearch v0.1.4
  [d3d80556] LineSearches v7.3.0
  [7ed4a6bd] LinearSolve v3.7.2
  [2ab3a3ac] LogExpFunctions v0.3.29
  [d8e11817] MLStyle v0.4.17
  [1914dd2f] MacroTools v0.5.15
  [d125e4d3] ManualMemory v0.1.8
  [bb5d69b7] MaybeInplace v0.1.4
  [e1d29d7a] Missings v1.2.0
  [961ee093] ModelingToolkit v9.72.0
  [2e0e35c7] Moshi v0.3.5
  [46d2c3a1] MuladdMacro v0.2.4
  [102ac46a] MultivariatePolynomials v0.5.7
  [d8a4904e] MutableArithmetics v1.6.4
  [d41bc354] NLSolversBase v7.9.1
  [77ba4419] NaNMath v1.1.3
  [8913a72c] NonlinearSolve v4.6.0
  [be0214bd] NonlinearSolveBase v1.5.2
  [5959db7a] NonlinearSolveFirstOrder v1.3.1
  [9a2c21bd] NonlinearSolveQuasiNewton v1.2.1
  [26075421] NonlinearSolveSpectralMethods v1.1.1
  [6fe1bfb0] OffsetArrays v1.17.0
  [429524aa] Optim v1.12.0
  [bac558e1] OrderedCollections v1.8.0
  [6ad6398a] OrdinaryDiffEqBDF v1.4.0
  [bbf590c4] OrdinaryDiffEqCore v1.22.0
  [50262376] OrdinaryDiffEqDefault v1.3.0
  [4302a76b] OrdinaryDiffEqDifferentiation v1.6.0
  [127b3ac7] OrdinaryDiffEqNonlinearSolve v1.6.0
  [43230ef6] OrdinaryDiffEqRosenbrock v1.9.0
  [2d112036] OrdinaryDiffEqSDIRK v1.3.0
  [b1df2697] OrdinaryDiffEqTsit5 v1.1.0
  [79d7bb75] OrdinaryDiffEqVerner v1.1.1
  [90014a1f] PDMats v0.11.34
  [d96e819e] Parameters v0.12.3
  [e409e4f3] PoissonRandom v0.4.4
  [f517fe37] Polyester v0.7.16
  [1d0040c9] PolyesterWeave v0.2.2
  [85a6dd25] PositiveFactorizations v0.2.4
  [d236fae5] PreallocationTools v0.4.26
⌅ [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [08abe8d2] PrettyTables v2.4.0
  [27ebfcd6] Primes v0.5.7
  [43287f4e] PtrArrays v1.3.0
  [1fd47b50] QuadGK v2.11.2
  [74087812] Random123 v1.7.0
  [e6cf234a] RandomNumbers v1.6.0
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.31.2
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.1
  [ae5879a3] ResettableStacks v1.1.1
  [79098fc4] Rmath v0.8.0
  [7e49a35a] RuntimeGeneratedFunctions v0.5.13
  [9dfe8606] SCCNonlinearSolve v1.0.0
  [94e857df] SIMDTypes v0.1.0
  [0bca4576] SciMLBase v2.84.0
  [19f34311] SciMLJacobianOperators v0.1.2
  [c0aeaf25] SciMLOperators v0.3.13
  [53ae85a6] SciMLStructures v1.7.0
  [efcf1570] Setfield v1.1.2
  [727e6d20] SimpleNonlinearSolve v2.2.1
  [699a6c99] SimpleTraits v0.9.4
  [ce78b400] SimpleUnPack v1.1.0
  [a2af1166] SortingAlgorithms v1.2.1
  [0a514795] SparseMatrixColorings v0.4.18
  [276daf66] SpecialFunctions v2.5.1
  [aedffcd0] Static v1.2.0
  [0d7ed370] StaticArrayInterface v1.8.0
  [90137ffa] StaticArrays v1.9.13
  [1e83bf80] StaticArraysCore v1.4.3
  [10745b16] Statistics v1.11.1
  [82ae8749] StatsAPI v1.7.0
  [2913bbd2] StatsBase v0.34.4
  [4c63d2b9] StatsFuns v1.4.0
  [7792a7ef] StrideArraysCore v0.5.7
  [892a3eda] StringManipulation v0.4.1
  [2efcf032] SymbolicIndexingInterface v0.3.39
  [19f23fe9] SymbolicLimits v0.2.2
  [d1185830] SymbolicUtils v3.26.1
  [0c5d862f] Symbolics v6.38.0
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.0
  [ed4db957] TaskLocalValues v0.1.2
  [8ea1fca8] TermInterface v2.0.0
  [1c621080] TestItems v1.0.0
  [8290d209] ThreadingUtilities v0.5.3
  [a759f4b9] TimerOutputs v0.5.28
  [0796e94c] Tokenize v0.5.29
  [410a4b4d] Tricks v0.1.10
  [781d530d] TruncatedStacktraces v1.4.0
  [5c2747f8] URIs v1.5.2
  [3a884ed6] UnPack v1.0.2
  [1986cc42] Unitful v1.22.0
  [a7c27f48] Unityper v0.1.6
  [1d5cc7b8] IntelOpenMP_jll v2025.0.4+0
  [856f044c] MKL_jll v2025.0.1+1
  [efe28fd5] OpenSpecFun_jll v0.5.6+0
  [f50d1b31] Rmath_jll v0.5.1+0
  [1317d2d5] oneTBB_jll v2022.0.0+0
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [a63ad114] Mmap v1.11.0
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.11.0
  [de0858da] Printf v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [1a1011a3] SharedArrays v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.11.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] LibCURL_jll v8.6.0+0
  [e37daf67] LibGit2_jll v1.7.2+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.6+0
  [14a3606d] MozillaCACerts_jll v2023.12.12
  [4536629a] OpenBLAS_jll v0.3.27+1
  [05823500] OpenLibm_jll v0.8.1+4
  [bea87d4a] SuiteSparse_jll v7.7.0+0
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.11.0+0
  [8e850ede] nghttp2_jll v1.59.0+0
  [3f19e933] p7zip_jll v17.4.0+2
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
```

  - Output of `versioninfo()`

```julia
Julia Version 1.11.4
Commit 8561cc3d68d (2025-03-10 11:36 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × Intel(R) Core(TM) i9-14900K
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, alderlake)
Threads: 32 default, 0 interactive, 16 GC (on 32 virtual cores)
Environment:
  JULIA_EDITOR = code
```

**Additional context**

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Close #3570

### CODE REVIEW

File: src/systems/nonlinear/initializesystem.jl [hunk 1]
```diff
@@ -658,6 +659,18 @@ function SciMLBase.late_binding_update_u0_p(
         prob, sys::AbstractSystem, u0, p, t0, newu0, newp)
     supports_initialization(sys) || return newu0, newp
     u0 === missing && return newu0, (p === missing ? copy(newp) : newp)
+    # If the user passes `p` to `remake` but not `u0` and `u0` isn't empty,
+    # and if the system supports initialization (so it has initial parameters),
+    # and if the initialization solves for `u0`,
```
Comment (ChrisRackauckas) [inline src/systems/nonlinear/initializesystem.jl:664]: you don't know this.

Comment (AayushSabharwal) [reply src/systems/nonlinear/initializesystem.jl:596]: We do. Initialization solves for unknowns if `initializeprobmap !== nothing`

Comment (ChrisRackauckas) [reply src/systems/nonlinear/initializesystem.jl:596]: You don't know what the initialization will be until `solve` is called.

Comment (AayushSabharwal) [reply src/systems/nonlinear/initializesystem.jl:596]: We have all the information about the initialization in the `ODEProblem`?

Comment (ChrisRackauckas) [reply src/systems/nonlinear/initializesystem.jl:596]: We don't know which initialization method will be used until later. CheckInit and NoInit don't solve for u0.

**Comment by AayushSabharwal** [comment]
Waiting for https://github.com/SciML/DiffEqBase.jl/pull/1143

File: src/systems/nonlinear/initializesystem.jl [hunk 2]
```diff
@@ -646,6 +650,40 @@ function SciMLBase.late_binding_update_u0_p(
...
+    u0 === nothing && return prob
+
+    p = parameter_values(prob)
+    t0 = is_time_dependent(prob) ? current_time(prob) : nothing
+    meta = initdata.metadata
+
+    getter = if meta isa InitializationMetadata
+        meta.get_initial_unknowns
+    else
+        getu(sys, Initial.(unknowns(sys)))
```
Comment (ChrisRackauckas) [inline src/systems/nonlinear/initializesystem.jl:668]: I assume this will get the guesses too?

File: src/systems/nonlinear/initializesystem.jl [hunk 3]
```diff
@@ -646,6 +650,40 @@ function SciMLBase.late_binding_update_u0_p(
...
+    end
+
+    u0 = DiffEqBase.promote_u0(u0, buffer, t0)
+
+    if ArrayInterface.ismutable(u0)
+        T = typeof(u0)
+    else
+        T = StaticArrays.similar_type(u0)
+    end
+    return remake(prob; u0 = T(getter(p)))
```
Comment (ChrisRackauckas) [inline src/systems/nonlinear/initializesystem.jl:684]: does this need like `build_initializationprob = false` or other things to skip redoing a symbolic remake?

Comment (AayushSabharwal) [reply src/systems/nonlinear/initializesystem.jl:684]: The case where `u0` is a non-symbolic vector doesn't do symbolic remake, it simply promotes the initialization problem.

File: src/systems/nonlinear/initializesystem.jl (hunk 2 above)
Comment (AayushSabharwal) [reply src/systems/nonlinear/initializesystem.jl:668]: Why would the guesses come into the picture here?

Comment (ChrisRackauckas) [reply src/systems/nonlinear/initializesystem.jl:668]: It's the same reason as https://github.com/SciML/SciMLSensitivity.jl/pull/1168/files#diff-76127b1004a68143584d305e1c9ee36126238fd5a05ddeff5985f5b5450ed2c2R92, the `u0` vector on DAEs is canonically interpreted as either the initial value or the guess for `u0`, depending on the choice of initialization and which one exists.

Comment (AayushSabharwal) [reply src/systems/nonlinear/initializesystem.jl:668]: I see. That's a little more annoying, but not difficult to do. I'll fix it so this propagates guesses.

Comment (AayushSabharwal) [reply src/systems/nonlinear/initializesystem.jl]: Fixed now

**Comment by AayushSabharwal** [comment]
Cancelled CI because I forgot to add a test

**Comment by AayushSabharwal** [comment]
SciMLBase/Downstream failure is https://github.com/SciML/SciMLBase.jl/pull/1006. `pre` seems to be failing because NonlinearSolve doesn't precompile

**Review by ChrisRackauckas — APPROVED** [review]
