### PR TITLE
Handle dependencies of observed variables properly

### LINKED ISSUE #834: Calculating observed variables which are functions of algebraic variables fails
The new acausal modeling tutorial is the MWE for this.

### PR DESCRIPTION
**Pull request by YingboMa**
Fix #834

### CODE REVIEW

File: src/systems/nonlinear/nonlinearsystem.jl [hunk 1]
```diff
@@ -60,7 +61,7 @@ function NonlinearSystem(eqs, states, ps;
     default_p isa Dict || (default_p = Dict(default_p))
     default_u0 = Dict(value(k) => value(default_u0[k]) for k in keys(default_u0))
     default_p = Dict(value(k) => value(default_p[k]) for k in keys(default_p))
-    NonlinearSystem(eqs, value.(states), value.(ps), observed, name, systems, default_u0, default_p, nothing)
+    NonlinearSystem(eqs, value.(states), value.(ps), observed, name, systems, default_u0, default_p, nothing, [])
```
Comment (ChrisRackauckas) [inline src/systems/nonlinear/nonlinearsystem.jl:64]: so we need this in all systems?

Comment (YingboMa) [reply src/systems/nonlinear/nonlinearsystem.jl:64]: Only for systems that support `structural_simplify`.

File: docs/src/tutorials/acausal_components.md [hunk 2]
```diff
@@ -12,7 +12,7 @@ equalities before solving. Let's see this in action.
 ## Copy-Paste Example
 
 ```julia
-using ModelingToolkit, Plots
+using ModelingToolkit, Plots, OrdinaryDiffEq
```
Comment (ChrisRackauckas) [inline docs/src/tutorials/acausal_components.md:15]:
```suggestion
using ModelingToolkit, Plots, DifferentialEquations
```
