### PR TITLE
Protecting `bound_parameters` with `iscomplete` check

### LINKED ISSUE #4346: `SII.all_symbols` errors on non-complete system in MTK@11
**Describe the bug 🐞**
When called on a non-complete system, SII.all_symbols errors. Used to work on MTKv10

**Minimal Reproducible Example 👇**

```julia
using ModelingToolkitBase
using ModelingToolkitBase: t_nounits as t
using SymbolicIndexingInterface: SymbolicIndexingInterface as SII
@variables x(t)
sys = System(Equation[], t, [x], []; name=:sys)
SII.all_symbols(sys)
```

**Error & Stacktrace ⚠️**

```julia
ERROR: `bound_parameters` requires a completed system.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:44
 [2] bound_parameters
   @ ~/.julia/packages/ModelingToolkitBase/1xRSH/src/systems/abstractsystem.jl:1630 [inlined]
 [3] all_symbols(sys::System)
   @ ModelingToolkitBase ~/.julia/packages/ModelingToolkitBase/1xRSH/src/systems/abstractsystem.jl:466
 [4] top-level scope
   @ REPL[12]:1
 [5] top-level scope
   @ REPL:1
```

### PR DESCRIPTION
**Pull request by cmhyett**
## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API
  
## Additional context
Fixes #4346

### CODE REVIEW

File: lib/ModelingToolkitBase/test/abstractsystem.jl [hunk 1]
```diff
@@ -26,3 +27,26 @@ struct MyMVS <: MT.AbstractSystem
...
 @test all(isequal.(ivs, [t, x]))
+
+@testset "all_symbols on non-complete system" begin
+    @variables y(t)
+    @parameters p1 p2 = 2p1
+    sys = MT.System(Equation[], t, [y], [p1, p2]; name = :sys)
+
+    # Should not throw on a non-complete system
+    syms = SII.all_symbols(sys)
+    @test y ∈ syms
```
Comment (AayushSabharwal) [inline lib/ModelingToolkitBase/test/abstractsystem.jl]: You'll have to use `any(isequal(y), syms)` since `in` is overloaded to be symbolic
