### PR TITLE
fix: Throw better warning when a guess is missing 

### LINKED ISSUE #3449: Better error message for missing guesses
Currently errors for missing guesses say "missing initial value" or "circular initial condition" (depending on where it originates). See:
```julia
ERROR: LoadError: Found symbolic value <<VALUE>> for variable <<VARIABLE>>. You may be missing an initial condition or have cyclic initial conditions. If this is intended, pass `symbolic_u0 = true`. In case the initial conditions are not cyclic but require more substitutions to resolve, increase `substitution_limit`. To report cycles in initial conditions of unknowns/parameters, pass `warn_cyclic_dependency = true`. If the cycles are still not reported, you may need to pass a larger value for `circular_dependency_max_cycle_length` or `circular_dependency_max_cycles`.


Stacktrace:
  [1] better_varmap_to_vars(varmap::Dict{Any, Any}, vars::Vector{SymbolicUtils.BasicSymbolic{Real}}; tofloat::Bool, use_union::Bool, container_type::Type, toterm::Function, promotetoconcrete::Nothing, check::Bool, allow_symbolic::Bool)
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/41wGH/src/systems/problem_utils.jl:340
  [2] process_SciMLProblem(constructor::Type, sys::ModelingToolkit.NonlinearSystem, u0map::Dict{Any, Any}, pmap::Dict{Any, Any}; build_initializeprob::Bool, implicit_dae::Bool, t::Nothing, guesses::Dict{Any, Any}, warn_initialize_determined::Bool, initialization_eqs::Vector{Any}, eval_expression::Bool, eval_module::Module, fully_determined::Nothing, check_initialization_units::Bool, tofloat::Bool, use_union::Bool, u0_constructor::typeof(identity), du0map::Nothing, check_length::Bool, symbolic_u0::Bool, warn_cyclic_dependency::Bool, circular_dependency_max_cycle_length::Int64, circular_dependency_max_cycles::Int64, substitution_limit::Int64, use_scc::Bool, kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/41wGH/src/systems/problem_utils.jl:720
```

This error message should instead report a missing guess, since it is currently very misleading. The only way for a user to differentiate is via the stacktrace, which is bad for any number of reasons.

### PR DESCRIPTION
**Pull request by vyudu**
Fix #3449

### CODE REVIEW

File: test/initial_values.jl [hunk 1]
```diff
@@ -172,7 +172,7 @@ end
             [p => 2q, q => 3p]; warn_cyclic_dependency = true)
     catch
     end
-    @test_throws ModelingToolkit.UnexpectedSymbolicValueInVarmap ODEProblem(
+    @test_throws ModelingToolkit.MissingGuessError ODEProblem(
```
Comment (vyudu) [inline test/initial_values.jl:175]: This is one of those cases that I'm not sure about, should this throw the MissingGuessError?

File: src/systems/problem_utils.jl [hunk 2]
```diff
@@ -325,6 +325,26 @@ function Base.showerror(io::IO, err::UnexpectedSymbolicValueInVarmap)
...
+            """
+            Unable to resolve numeric guesses for all of the variables in the system. \
+            This may be because your guesses are cyclic.
+
+            In order for the problem to be initialized, all of the variables must have \
+            a numeric value to serve as a starting point for the nonlinear solve. \
+            Please provide one or more additional numeric guesses to `guesses` in \
+            the problem constructor.
+
+            This error was thrown because symbolic value $(err.val) was found for variable $(err.sym).
```
Comment (ChrisRackauckas) [inline src/systems/problem_utils.jl:344]: only one?

File: test/initial_values.jl (hunk 1 above)
Comment (ChrisRackauckas) [reply test/initial_values.jl:175]: Yes, p and q would be missing and need a guess.

File: src/systems/problem_utils.jl (hunk 2 above)
Comment (SebastianM-C) [reply src/systems/problem_utils.jl:344]: I think the message is a bit confusing since one could interpret it as asking for more than one guess for a single variable.

Comment (vyudu) [reply src/systems/problem_utils.jl:344]: Ah okay, will change

**Comment by vyudu** [comment]
Assuming test pass I think this is good

File: src/systems/problem_utils.jl [hunk 3]
```diff
@@ -325,6 +325,27 @@ function Base.showerror(io::IO, err::UnexpectedSymbolicValueInVarmap)
...
+            Unable to resolve numeric guesses for all of the variables in the system. \
+            This may be because your guesses are cyclic. In order for the problem to be \
+            initialized, all of the variables must have a numeric value to serve as a \
+            starting point for the nonlinear solve. 
+
+            Symbolic values were found for the following variables/parameters in the map; \
+            please provide additional numeric guesses so they can resolve to numbers:
+            """)
+    for (sym, val) in zip(err.syms, err.vals)
+        println(sym, " => ", val)
```
Comment (ChrisRackauckas) [inline src/systems/problem_utils.jl:345]: If it's just missing, what's the val?

Comment (vyudu) [reply src/systems/problem_utils.jl:345]: The symbolic value that it tries to assign to the variable

Comment (ChrisRackauckas) [reply src/systems/problem_utils.jl:345]: That's if it's cyclic. But this also is for if a guess is just missing, right? In which case, what does the error look like?

Comment (vyudu) [reply src/systems/problem_utils.jl:345]: If a guess it just missing it throws a different error (IncompleteInitializationError)

**Comment by ChrisRackauckas** [comment]
```julia
    @parameters g
    @variables x(t) y(t) [state_priority = 10] λ(t)
    eqs = [D(D(x)) ~ λ * x
           D(D(y)) ~ λ * y - g
           x^2 + y^2 ~ 1]
    @mtkbuild pend = ODESystem(eqs, t)

    @test_throws ModelingToolkit.MissingGuessError ODEProblem(pend, [x => 1], (0, 1), [g => 1], guesses = [y => λ])
```

where it's missing a guess for `λ`, what does this print?

File: src/systems/problem_utils.jl (hunk 3 above)
Comment (vyudu) [reply src/systems/problem_utils.jl:345]: https://github.com/SciML/ModelingToolkit.jl/blob/0ad773d2b90009fa76e8d9f6ad681f91b73e73f1/src/systems/diffeqs/abstractodesystem.jl#L1345-L1353

Comment (ChrisRackauckas) [reply src/systems/problem_utils.jl:345]: That error doesn't make much sense to the user though? Why wouldn't the case I mentioned be a missing guess error?

**Comment by vyudu** [comment]
ERROR: Unable to resolve numeric guesses for all of the variables in the system. This may be because your guesses are cyclic. In order for the problem to be initialized, all of the variables must have a numeric value to serve as a starting point for the nonlinear solve.

Symbolic values were found for the following variables/parameters in the map; please provide additional numeric guesses so they can resolve to numbers:

y(t) => 50 + λ(t)
λ(t) => 2551 + y(t)

**Comment by ChrisRackauckas** [comment]
```
y(t) => 50 + λ(t)
λ(t) => 2551 + y(t)
```

how does it get that? That doesn't look right.

What does it print for:

```julia
    @parameters g
    @variables x(t) y(t) [state_priority = 10] λ(t)
    eqs = [D(D(x)) ~ λ * x
           D(D(y)) ~ λ * y - g
           x^2 + y^2 ~ 1]
    @mtkbuild pend = ODESystem(eqs, t)

    ODEProblem(pend, [x => 1], (0, 1), [g => 1])
```

?

File: src/systems/problem_utils.jl (hunk 3 above)
Comment (vyudu) [reply src/systems/problem_utils.jl:345]: there is also this error but I need to dig a bit to figure out when it throws IncompleteInitializationError vs this one, maybe @AayushSabharwal knows better
https://github.com/SciML/ModelingToolkit.jl/blob/0ad773d2b90009fa76e8d9f6ad681f91b73e73f1/src/variables.jl#L210-L214

**Comment by vyudu** [comment]
Sorry, the first case you posted actually prints this, my output was from the test I wrote

      Initial condition underdefined. Some are missing from the variable map.
      Please provide a default (`u0`), initialization equation, or guess
      for the following variables:

      λ(t)

**Comment by ChrisRackauckas** [comment]
Okay so if any are missing you get that message, and if it's cyclic you get this other method. Given that, can we refine the error message? We know it's not a missing guess and instead a cyclic case, so we should make this more explicit.
