### PR TITLE
handle empty events

### LINKED ISSUE #1409: Using `continuous_events` on `connect`ed circuits/systems
```julia
using ModelingToolkitStandardLibrary.Electrical, ModelingToolkit, OrdinaryDiffEq
using ModelingToolkitStandardLibrary.Electrical: Ground, Resistor, VoltageSensor, VoltageSource, Pin
using ModelingToolkitStandardLibrary.Blocks: SmoothSineFunction
# VoltageSource and SmoothSineFunction from this PR <https://github.com/SciML/ModelingToolkitStandardLibrary.jl/pull/18/files>

function StepFunction(;name, offset=0.0, starttime=0.0, height=1.0)
    o, st, h = offset, starttime, height

    @parameters offset starttime height
    @variables y(t)

    eqs = [
           y ~ offset + h * (t > st)
          ]
    defaults = Dict(zip((offset, starttime, height), (o, st, h)))
    ODESystem(eqs, t, [y], [offset, starttime, height],
              defaults=defaults, name=name)
              # continuous_events=[t ~ st] => [y ~ h])
end

st = 0.5
@parameters t
@named ground = Ground()
@named resistor = Resistor()
@named source = VoltageSource()
@named stepp = StepFunction(offset=0.4, starttime=0.5, height=4)
@named voltage_sensor = VoltageSensor()

rc_eqs = [
    source.v ~ stepp.y
    connect(source.p, resistor.p, voltage_sensor.p)
    connect(voltage_sensor.n, source.n, resistor.n, ground.g)
]

@named rc_model = ODESystem(rc_eqs, t, systems = [resistor, stepp, 
    source, voltage_sensor, ground],
    continuous_events = [t ~ st] => [source.v ~ h]
    )

sys = structural_simplify(rc_model)
prob(ODEProblem(sys, u0, (0, 2.0))
```
results `LoadError: BoundsError: attempt to access 13-element Vector{Function} at index []
Stacktrace:`

The `ModelingToolkit.continuous_events(sys)` has following output
```
13-element Vector{ModelingToolkit.SymbolicContinuousCallback}:
 ModelingToolkit.SymbolicContinuousCallback(Equation[t ~ 0.5], Equation[source₊v(t) ~ 2.5])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
```

This no. 13 represents the no. of components used (5 directly in the rc_eqs and the `Pins` that connect them. Specifying a `continuous_events` for each of the used component fixes this issue. But  a `continuous_events` for `Pin` doesn't seem like a necessity.

_Sidenote: Even a dummy like `continuous_events=1~0` at the component level by-passes the above error_

Also, @variables in lower level continuous events must be mentioned in the final model (here `rc_model`).
For example, in the `StepFunction` above if `continuous_events`, instead of `t` which is passed to `rc_model`, is defined for `y` or any new variable then eventual `solve` throws `LoadError: UndefVarError: stepp₊y not defined`

### LINKED ISSUE #1528: Assertion fails when building event callbacks
When composing a system with MTK (8.7.0), empty callbacks (i.e. of the form `ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])`) are sometimes created. These callbacks seem to trip the assertion on https://github.com/SciML/ModelingToolkit.jl/blob/7945b36f88d830dfecb0bb5463228849b297ba75/src/systems/diffeqs/abstractodesystem.jl#L221

Here's code for reproducing the issue: https://gist.github.com/DaniGlez/22c98bd7d8b3bba479cf98082c62da56
In this example, four callbacks end up in the system after structural_simplify():

`4-element Vector{ModelingToolkit.SymbolicContinuousCallback}:
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])
 ModelingToolkit.SymbolicContinuousCallback(Equation[m₊x(t) ~ 1.0], Equation[m₊v(t) ~ -m₊v(t)])
 ModelingToolkit.SymbolicContinuousCallback(Equation[m₊x(t) ~ -1.0], Equation[m₊v(t) ~ -m₊v(t)])
 ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])`
 
The assertion mentioned above therefore fails, since the largest index mapping to an affect is 3 while there are four affect functions (even if the last one is a dummy function)

### PR DESCRIPTION
**Pull request by baggepinnen**
Closes #1528 
Closes #1409

### CODE REVIEW

File: src/systems/abstractsystem.jl [hunk 1]
```diff
@@ -482,11 +483,13 @@ end
...
     obs = get_continuous_events(sys)
+    filter(!isempty, obs)
     systems = get_systems(sys)
-    [obs;
-     reduce(vcat,
+    cbs = [obs;
+    reduce(vcat,
             (map(o->namespace_equation(o, s), continuous_events(s)) for s in systems),
             init=SymbolicContinuousCallback[])]
+    filter(!isempty, cbs)
```
Comment (YingboMa) [inline src/systems/abstractsystem.jl:492]: If the leafs are always nonempty by line 486, do you need the filter here?

Comment (YingboMa) [reply src/systems/abstractsystem.jl:492]: ah, systems could be empty.

**Review by YingboMa — APPROVED** [review]
