### PR TITLE
Fixing ignored initial conditions

### LINKED ISSUE #4258: InitializationProblem ignores set initial conditions.
**Describe the bug 🐞**

`InitializationProblem` ignores set initial conditions.

**Expected behavior**

According to documentation, setting initial conditions should be a hard constraint on the problem, yet they are ignored.

**Minimal Reproducible Example 👇**

```julia
using ModelingToolkit, NonlinearSolve
using ModelingToolkit: t_nounits as t, D_nounits as D
@parameters g
@variables x(t) y(t) [state_priority = 10] λ(t)
eqs = [D(D(x)) ~ λ * x
       D(D(y)) ~ λ * y - g
       x^2 + y^2 ~ 1]
@mtkcompile pend = System(eqs, t)

# Explicitly set `x=>1.0`, but the problem/solution won't respect it and fails

iprob = ModelingToolkit.InitializationProblem(
    pend, 0.0,
    [x => 1.0, D(y) => 0.0, g => 1],
    guesses = [λ => 1, y => 0.0])
isol = solve(iprob)
isol.retcode
# ReturnCode.Stalled = 18
isol[isol.prob.f.sys.x]
# 0.0
isol[isol.prob.f.sys.y]
# 0.0
iprob.ps[Initial(x)]
# 0.0
iprob.ps[Initial(y)]
# 0.0
iprob.ps[Initial(x)] = 1.0
# 1.0
isol = solve(iprob)
# retcode: Success
# u: 3-element Vector{Float64}:
#   0.0
#  -0.0
#   0.0
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Project ModelingToolkit v11.9.0
Status `~/Projects/MTK_4215/ModelingToolkit.jl/Project.toml`
  [47edcb42] ADTypes v1.21.0
  [caf10ac8] BipartiteGraphs v0.1.6
  [8e7c35d0] BlockArrays v1.9.3
⌅ [861a8166] Combinatorics v1.0.2
  [38540f10] CommonSolve v0.2.6
  [864edb3b] DataStructures v0.19.3
  [2b5f629d] DiffEqBase v6.200.0
  [a0c0ee7d] DifferentiationInterface v0.7.16
  [ffbed154] DocStringExtensions v0.9.5
  [1a297f60] FillArrays v1.16.0
  [64ca27bc] FindFirstFunctions v1.8.0
  [f6369f11] ForwardDiff v1.3.2
  [86223c79] Graphs v1.13.4
  [7771a370] ModelingToolkitBase v1.10.0
  [6bb917b9] ModelingToolkitTearing v1.2.5
  [2e0e35c7] Moshi v0.3.7
  [8913a72c] NonlinearSolve v4.15.0
  [6fe1bfb0] OffsetArrays v1.17.0
  [bac558e1] OrderedCollections v1.8.1
  [1dea7af3] OrdinaryDiffEq v6.108.0
  [91a5bcdd] Plots v1.41.4
  [d236fae5] PreallocationTools v1.1.2
⌅ [aea7be01] PrecompileTools v1.2.1
  [189a3867] Reexport v1.2.2
  [7e49a35a] RuntimeGeneratedFunctions v0.5.17
  [9dfe8606] SCCNonlinearSolve v1.9.0
  [0bca4576] SciMLBase v2.136.0
  [431bcebd] SciMLPublic v1.0.1
  [efcf1570] Setfield v1.1.2
  [727e6d20] SimpleNonlinearSolve v2.10.0
  [64909d44] StateSelection v1.3.0
  [90137ffa] StaticArrays v1.9.16
  [3384d301] SymbolicCompilerPasses v0.1.1
  [2efcf032] SymbolicIndexingInterface v0.3.46
  [d1185830] SymbolicUtils v4.16.0
  [0c5d862f] Symbolics v7.11.0
  [3a884ed6] UnPack v1.0.2
  [b77e0a4c] InteractiveUtils v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [3fa0cd96] REPL v1.11.0
  [9e88b42a] Serialization v1.11.0
  [2f01184e] SparseArrays v1.11.0
```

  - Output of `versioninfo()`

```julia
Julia Version 1.11.8
Commit cf1da5e20e3 (2025-11-06 17:49 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 22 × Intel(R) Core(TM) Ultra 9 185H
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, alderlake)
Threads: 10 default, 0 interactive, 5 GC (on 22 virtual cores)
Environment:
  JULIA_NUM_THREADS = 10
```

### PR DESCRIPTION
**Pull request by cmhyett**
Fixes #4258. In `InitializationProblem`, `op = build_operating_point(sys, op)`, and then later is mutated by `generate_intializationsystem`, inside of which if `fast_path == false` `op` is assigned a new copy via the same command `op = build_operating_point(sys, op)`. As `sys` is not modified between the first and second calls, it is equivalent to toggle the `fast_path` flag after constructing `op` the first time. This avoids destroying the reference to the caller object, allowing the mutation to persist after returning.

## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API

### CODE REVIEW

**Comment by cmhyett** [comment]
I think ready for review @ChrisRackauckas, @AayushSabharwal (I believe test failures are from main?)

**Comment by cmhyett** [comment]
I might just add that `generate_initializesystem` needs some attention. 
Talked to Aayush about it, and learned its behavior is important. Unfortunately it claims to not be mutating, but it _sometimes is_ (depending on which optional keyword arguments are provided; namely `op` and `guesses`), and we _sometimes_ rely on the mutating behavior.

Bigger fix that I didn't want to pull the string on here: 
- [ ] create mutating form `generate_initializesystem!`
- [ ] encapsulate mutation from subroutines
- [ ] provide `generate_initializesystem` that uses non-mutating subroutines and `generate_initializesystem!` that mutates

Explicit goals are that
- only code duplication occurs in the mutating subroutines
- public API isn't broken (namely `generate_initializesystem`) though if callers relied on the hidden behavior they'd be unhappy, but would only need to add `!` to their calls.

File: lib/ModelingToolkitBase/test/respect_ics.jl [hunk 1]
```diff
@@ -0,0 +1,28 @@
+using ModelingToolkit, NonlinearSolve
+using ModelingToolkit: t_nounits as t, D_nounits as D
+using Test
+
+@testset "ensure ICs are respected" begin
```
Comment (AayushSabharwal) [inline lib/ModelingToolkitBase/test/respect_ics.jl]: Thanks! The fix looks accurate. A small request: could you move this to the `initialization.jl` test file, and mention the issue number (#4258) in the `@testset`?

Comment (cmhyett) [reply lib/ModelingToolkitBase/test/respect_ics.jl]: I only see `initializationproblem.jl` and `initial_values.jl`. Which do you prefer?

Comment (AayushSabharwal) [reply lib/ModelingToolkitBase/test/respect_ics.jl]: Ah, I apologize for the typo. `initializationsystem.jl` would be best, and since this requires ModelingToolkit it should be inside an `if @isdefined(ModelingToolkit) ... end` block.

I made some changes to how initialization problems are handled recently, so it would be good to rebase this PR as well to make sure nothing breaks.

File: lib/ModelingToolkitBase/src/systems/codegen.jl [hunk 2]
```diff
@@ -1411,7 +1411,7 @@ function calculate_A_b(sys::System; sparse = false, throw = true)
         lex = Symbolics.LinearExpander(var; strict = true)
         for (i, resid) in enumerate(rhss)
             p, q, islinear = lex(resid)
-            if !islinear
+            if (!islinear || !isempty(Symbolics.get_variables(p, dvs)))
```
Comment (cmhyett) [inline lib/ModelingToolkitBase/src/systems/codegen.jl]: @AayushSabharwal please check. This fix was required to get the Lotka-Voltera system in `initialization.md` to compile and solve.

Namely the bilinear terms in the equations
```
D(y) ~ -\gamma * y + \delta * x * y
```
would pass the `!islinear` check, but would leave variables in the codegen.

**Comment by cmhyett** [comment]
With this last fix, the `initialization.md` docs should build and example blocks should execute again. 
- Fixes #3917

Set up issue #4317  that pinpoints underlying problem for #4214 and #4177

File: lib/ModelingToolkitBase/src/systems/codegen.jl (hunk 2 above)
Comment (AayushSabharwal) [reply lib/ModelingToolkitBase/src/systems/codegen.jl]: Oh, that's a nasty bug. Thanks for finding it. While the check is technically correct, it is _very_ expensive. Can we merge without this fix, even if the docs are a little broken? I'll try and find a cheaper way to do the check. It'll likely require some changes to Symbolics to expose a little more API.

File: test/runtests.jl [hunk 3]
```diff
@@ -65,6 +65,7 @@ end
         @safetestset "Hierarchical Initialization Equations" include("hierarchical_initialization_eqs.jl")
         @mtktestset("InitializationSystem Test", "initializationsystem.jl")
         @mtktestset("Initial Values Test", "initial_values.jl")
+        @mtktestset("MTK respects ICs", "respect_ics.jl")
```
Comment (AayushSabharwal) [inline test/runtests.jl]:
```suggestion
```
